version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: rushschool-mongo1
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - rushschool-net
    

  backend:
    build: ./backend
    container_name: rushschool-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - rushschool-net

  frontend:
    build: ./frontend
    container_name: rushschool-frontend
    restart: always
    env_file:
      - ./frontend/.env.local
    ports:
      - "3002:3002"
    depends_on:
      - backend
    networks:
      - rushschool-net

volumes:
  mongo-data:

networks:
  rushschool-net:
    driver: bridge
